---
title: "Download single-cell data from Allen Brain Map"
output: html_document

---
Download the human single cell data from
[Allen Institute for Brain Science](https://portal.brain-map.org/atlases-and-data/rnaseq/human-multiple-cortical-areas-smart-seq).

#download data

1. download reference genome files (.gtf)
```{r}
rm(list=ls())
url <- "http://celltypes.brain-map.org/api/v2/well_known_file_download/502175284"

destfile <- "reference.gtf"

download.file(url, destfile)

```

2. download general data

```{r}

#Readme file

url1 <- "https://brainmapportal-live-4cc80a57cd6e400d854-f7fdcae.divio-media.net/filer_public/30/80/30803016-9515-45fd-a6af-8595902c176f/readme_human_ctx.txt"

destfile1 <- "readme.txt"

download.file(url1, destfile1)

#table of cell metadata
url2 <- "https://idk-etl-prod-download-bucket.s3.amazonaws.com/aibs_human_ctx_smart-seq/metadata.csv"

destfile2 <- "metadata.csv"

download.file(url2, destfile2)

#table of cell metata_MTG

url2 <- "https://github.com/AllenInstitute/nomenclature/raw/master/data/cell_metadata_MTG.csv"

destfile2 <- "metadata_MTG.csv"

download.file(url2, destfile2)


#2D coordinates
url3 <- "https://idk-etl-prod-download-bucket.s3.amazonaws.com/aibs_human_ctx_smart-seq/tsne.csv"

destfile3 <- "2D.coordinates.csv"

download.file(url3, destfile3)

#sample ID mapping
url4 <- "https://brainmapportal-live-4cc80a57cd6e400d854-f7fdcae.divio-media.net/filer_public/b1/9f/b19f5e10-c6b2-4cf4-80fc-182e69a4511f/sample-exp_component_mapping_human_smart-seq_oct_2019.zip"

destfile4 <- "sampleIDmapping.csv"

download.file(url4, destfile4)

```


3. download gene expression data


```{bash}


#gene expression matrix 

wget "https://idk-etl-prod-download-bucket.s3.amazonaws.com/aibs_human_ctx_smart-seq/matrix.csv"

#Intronic reads expression matrix 

wget "https://idk-etl-prod-download-bucket.s3.amazonaws.com/aibs_human_ctx_smart-seq/intron.csv"


#Exonic reads expression matrix 
wget "https://idk-etl-prod-download-bucket.s3.amazonaws.com/aibs_human_ctx_smart-seq/exon.csv"


#Gene expression by cluster, trimmed means
wget "https://idk-etl-prod-download-bucket.s3.amazonaws.com/aibs_human_ctx_smart-seq/trimmed_means.csv"

#Gene expression by cluster, medians
wget "https://idk-etl-prod-download-bucket.s3.amazonaws.com/aibs_human_ctx_smart-seq/medians.csv"

```


4. download cell types taxonomy


```{r}
rm(list=ls())

#taxonomy of cell types

url1 <- "https://idk-etl-prod-download-bucket.s3.amazonaws.com/aibs_human_ctx_smart-seq/dend.json"

destfile1 <- "celltype.json"

download.file(url1, destfile1)

#taxonomy information

url2 <- "https://transcriptomic-viewer-downloads.s3-us-west-2.amazonaws.com/human/taxonomy.zip"

destfile2 <- "taxinfo.txt"

download.file(url2, destfile2)

```


